# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
image: frekele/ant:latest
stages:
- build
- test
build:
  stage: build
  script:
  - cd server && ant compile_core && ant compile_plugins && cd ../
  - cd Client_Base && ant compile && cd ../
  - cd PC_Launcher && ant compile && cd ../
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
